name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Only run on PR comments that contain "/claude review"
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '/claude review'))
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          # Required: Your Anthropic API key
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Optional: Choose the model (default: claude-3-5-sonnet-20241022)
          model: claude-3-5-sonnet-20241022
          
          # Optional: Custom review prompt
          review-prompt: |
            Please review this code and provide feedback on:
            1. Code quality and best practices
            2. Potential bugs or issues
            3. Performance considerations
            4. Security concerns
            5. Suggestions for improvement
            
            Be constructive and specific in your feedback.
          
          # Optional: Max files to review (default: 20)
          max-files: 20
          
          # Optional: File patterns to include/exclude
          include-patterns: |
            **/*.js
            **/*.ts
            **/*.jsx
            **/*.tsx
            **/*.py
            **/*.go
            **/*.java
          
          exclude-patterns: |
            **/*.test.*
            **/*.spec.*
            **/node_modules/**
            **/dist/**
            **/build/**